<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:schema="http://xmlns.example.com/customers"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  targetNamespace="http://xmlns.example.com/customers">

  <wsdl:types xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
               xmlns:tns="http://xmlns.example.com/customers"
               elementFormDefault="qualified"
               targetNamespace="http://xmlns.example.com/customers">
      <xs:import namespace="http://xmlns.example.com/customers" schemaLocation="customers.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema"/>
    </xs:schema>
  </wsdl:types>

  <wsdl:message name="GetCustomerRequest" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:part element="schema:GetCustomerRequest" name="GetCustomerRequest" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetCustomerResponse" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:part element="schema:GetCustomerResponse" name="GetCustomerResponse" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"></wsdl:part>
  </wsdl:message>

  <wsdl:portType name="customersWS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:operation name="GetCustomer" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
      <wsdl:input message="schema:GetCustomerRequest" name="GetCustomerRequest" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"></wsdl:input>
      <wsdl:output message="schema:GetCustomerResponse" name="GetCustomerResponse" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"></wsdl:output>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="customersWSBinding" type="schema:customersWS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
    <wsdl:operation name="GetCustomer" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
      <soap:operation soapAction="" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
      <wsdl:input name="GetCustomerRequest" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
        <soap:body use="literal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
      </wsdl:input>
      <wsdl:output name="GetCustomerResponse" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
        <soap:body use="literal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

</wsdl:definitions>